# Generated by Django 6.0 on 2025-12-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyerProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
