# Generated by Django 6.0 on 2026-02-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_incomeorcostpermonth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomeorcostpermonth',
            old_name='monthAndYear',
            new_name='month_and_year',
        ),
    ]
