# Generated by Django 6.0 on 2026-02-03 17:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
