# Generated by Django 6.0 on 2026-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_serviceimage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
