# Generated by Django 6.0 on 2026-01-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Not paid', 'Not paid'), ('Active', 'Active'), ('Paid', 'Paid')], default='Not paid', max_length=20),
        ),
    ]
