# Generated by Django 6.0 on 2026-01-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Not paid'), ('Paid', 'Paid'), ('Active', 'Active'), ('Canceled', 'Canceled')], default='Not paid', max_length=20),
        ),
    ]
