# Generated by Django 6.0 on 2026-01-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Not paid'), ('Active', 'Active'), ('Canceled', 'Canceled'), ('Paid', 'Paid')], default='Not paid', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
