# Generated by Django 6.0 on 2026-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Not paid'), ('Paid', 'Paid'), ('Active', 'Active'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Not paid', max_length=20),
        ),
    ]
